name: core_api_service
description: Core Api Service use dio package
version: 1.0.0
repository: https://github.com/anjarnaufals/core_api_service.git
environment:
  sdk: ^3.0.5

# Add regular dependencies here.
dependencies:
  dio: ^5.2.1+1
  dio_smart_retry: ^5.0.0
# path: ^1.8.0
dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
